### ISSUE TITLE
 rsuite-color-picker in Dropdown menu

### ISSUE THREAD

**Issue by Masarsah** [cXiaof/rsuite-color-picker#9]
Hi, I'm using rsuite-color-picker and put it in dropdown item when I click doesn't render instead it close the menu dropdown

**Comment by Masarsah** [comment]
`                  <Dropdown.Item componentClass="div">    <ColorPicker defaultValue={mcolor} onChange={(value)=>setMColor(value) } /></Dropdown.Item>
                  <Dropdown.Item componentClass="div">    <ColorPicker defaultValue={pColor} onChange={(value)=>setPColor(value) } /></Dropdown.Item>
`

**Comment by cXiaof** [comment]
maybe you can try using `<Dropdown.Item>` props **`renderItem`**
like this
```javascript
<Dropdown.Item renderItem={() => <ColorPicker />} />
```

**Comment by Masarsah** [comment]
thank you it work
